name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]

    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
      - name: Set up python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v3.2.4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install pip dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd test && pytest